PIPELINE: 'CloudMask'
DATAMODULE: null
MODEL:
  PREPROCESSOR:
    NAME: '' # acceptable is mlp or conv
    HIDDEN_DIMS: [16,16]
    CONV_KERNEL_SIZE: 3
  ENCODER: 'satvision'
  DECODER: 'fcn'
  PRETRAINED: /umbc/rs/nasa-access/users/xingyan/pytorch-caney/satvision-toa-giant-patch8-window8-128/mp_rank_00_model_states.pt
  TYPE: swinv2
  NAME: phasepredict16
  FREEZE_ALL: True
  FREEZE_LAYER: 3
  LORA: True
  LORA_RANK: 16
  VPT: False
  NUM_PROMPTS: 10
  IN_CHANS: 14
  DROP_PATH_RATE: 0.1
  SWINV2:
    IN_CHANS: 14
    EMBED_DIM: 512
    DEPTHS: [2, 2, 42, 2 ] # changed from 42 to 10
    NUM_HEADS: [ 16, 32, 64, 128]
    WINDOW_SIZE: 8
    NORM_PERIOD: 6
DATA:
  BATCH_SIZE: 256 
  DATA_PATHS: []
  TEST_DATA_PATHS: []
  IMG_SIZE: 128 
TRAIN:
  USE_CHECKPOINT: True
  EPOCHS: 40
  WARMUP_EPOCHS: 4
  BASE_LR: 5e-4 
  MIN_LR: 2e-4
  WARMUP_LR: 1e-4
  WEIGHT_DECAY: 0.05
  ACCELERATOR: 'gpu'
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
LOSS:
  NAME: 'focal'
PRECISION: "bf16"
PRINT_FREQ: 10 
SAVE_FREQ: 1
VALIDATION_FREQ: 10
TAG: CloudMask_LoRA_r32_14bands
